### ISSUE TITLE
Pangolin X11: Unable to retrieve framebuffer options on Xming Server

### ISSUE THREAD

**Issue by SkyRiderMike** [stevenlovegrove/Pangolin#242]
I found this issue on https://github.com/stevenlovegrove/Pangolin/issues/74#issuecomment-178248684, but i try the solution which is not useful on my computer.

I still meet this problem at latest stable build. My environment is running on Bash Ubuntu on Windows 10 and Xming Server. The glxgears application runs well on my computer.  I can even show an opencv window in my program. But pangolin fails..

The code compiled successfully, but still have problem with "Pangolin X11: Unable to retrieve framebuffer options ". What should I do ?

**Comment by stevenlovegrove** [comment]
Pangolin can actually build natively on Windows if you prefer (rather than using an X server). I'm afraid I don't have any experience with your configuration. I think you will have to debug that bit of code yourself (display_x11.cpp, line 116)

**Comment by jasminezz** [comment]
@SkyRiderMike  I have the same error at the latest stable build. My environment is running on Bash Ubuntu 16.04 on Windows 7 and Xming Server. Have u solved the problem?

**Comment by Pratapabhay** [comment]
@jasminezz I have similar problem at the latest build. Were you able to rectify the problem?

**Comment by a5192179** [comment]
I change Pangolin\src\display\device\display_x11.cpp and solve this problem.You can try:
change
 “GLX_DOUBLEBUFFER    , glx_doublebuffer ? True : False,”
to
“GLX_DOUBLEBUFFER    , False, //glx_doublebuffer ? True : False,”
then,
cmake,make,sudo make install
that's all.

**Comment by Andreachen0707** [comment]
@a5192179  Hi could you explain your solution in detail? I'm working on subsystem on Windows 10 and I encounter the exact same error. I tried your solution but it still cannot work.

Thanks in advance!

**Comment by siddhya** [comment]
Same here. Working on Ubuntu for Windows with Xming server. I tried the above solution but it does not work.

**Comment by GaneshPrabakaran** [comment]
I found a quick solution for this issue.
Replace the line below in display_x11.cpp as follows.
    //GLXFBConfig* fbc = glXChooseFBConfig(display, DefaultScreen(display), visual_attribs, &fbcount);
	GLXFBConfig* fbc = glXGetFBConfigs(display, DefaultScreen(display), &fbcount);

This will still give a warning "Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.". But it will be able to make the code running.

**Comment by xuwh15** [comment]
I am also facing the same problem with an ubuntu 16.04 virtual machine on google cloud. Any solutions?

**Comment by xuwh15** [comment]
@a5192179 Tried your solution, still not working...

**Comment by xuwh15** [comment]
@GaneshPrabakaran Are you using NVIDIA driver for fbconfig? How can I check my FBConfigs on linux system?

**Comment by siddhya** [comment]
I think it is an XServer version issue. It was not working for XLaunch on Windows but worked for MobaXterm which uses the latest version.

**Comment by GaneshPrabakaran** [comment]
@xuwh15 I am running in CPU and do not have NVIDIA driver. Xming for windows automatically resize the frame buffer. 

The method (glXChooseFBConfig) to retrieve fbconfigs with specific visual attributes returns null. Similarly, glXGetFBConfigs also do not provide any values for the attributes samples and sample buffer. Hence the warning message "Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts". glXGetFBConfigs returns some list of GLXFBConfig which helps resolve the error compared to glXChooseFBConfig which returns null.

**Comment by xuwh15** [comment]
@GaneshPrabakaran I have tried using glXGetFBConfigs and the same error still does not disappear. I tried to check my framebuffer settings but I do not have a /dev/fb0 on my ubuntu 16.04 virtual machine, I have googled it and most of the solutions worked for 12.04 and previous versions, I am not sure whether they worked for 16.04.

**Comment by xuwh15** [comment]
@GaneshPrabakaran Also, my glXGetFBConfigs still return the same error 
`Pangolin X11: Unable to retrieve framebuffer options`

**Comment by GaneshPrabakaran** [comment]
@xuwh15  I am using ubuntu 16.04 in windows 10 bash along with xming.

**Comment by siddhya** [comment]
@GaneshPrabakaran Use MobaXterm instead of Xming. That fixed the issue for me.

**Comment by xuwh15** [comment]
@GaneshPrabakaran I have checked the glxgetfbconfigs, and apparently there is no available fbconfigs to display, also the hellopangolin project does not work well on my virtual machine as well, is there anyway to install or set a frame buffer on ubuntu 16.04 system?

**Comment by HaoMyWorld** [comment]
You can try: change Pangolin\src\display\device\display_x11.cpp
L123-L124
//GLX_SAMPLE_BUFFERS , glx_sample_buffers,
//GLX_SAMPLES , glx_sample_buffers > 0 ? glx_samples : 0,

**Comment by yiakwy** [comment]
Please close this isssue. Mostly likely you are using NV driver and not doing good. Reinstall NV driver should resolve the display problems.

**Comment by liubamboo** [comment]
when I run orbslam2 on ubuntu server connected by ssh and xmanager. I have the same bug and I try the solution above all, but the bug still exist.

my bug info is terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options

anybody can help?

**Comment by maryraymond** [comment]
> I think it is an XServer version issue. It was not working for XLaunch on Windows but worked for MobaXterm which uses the latest version.

Thnx [siddhya](https://github.com/siddhya) this solved my problem
